### ISSUE TITLE
error massage

### ISSUE THREAD

**Issue by wenddymacro** [friosavila/csdid2#1]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/50739376/215629733-c885939c-6a1e-4a1a-86a7-26f7a39c0412.png">

**Comment by friosavila** [comment]
This means that the lcsdid.mlib file was not correctly copied on the
ado/personal folder
Also
Don’t forget to restart your Stata session
Fernando

**Comment by mu2023** [comment]
Dear Fernando, 

I am encountering the same error message as @wenddymacro. 
I copied all the files to my ado folder under folder "c", where the other csdid commands are also located. Assuming that the issue was lcdid.mlib file, I downloaded it separately, added it to the library, and restarted my Stata session. Yet, I still get the same error message. Could you please help me figure out what the reason could be? 

Thanks!

**Comment by friosavila** [comment]
For now I would suggest copying the lcsdid.mlib file in your personal folder
So, when starting Stata type
sysdir
And then just copy the mlib file in the "personal" address.

To see mata settings check
query mata
and verify if "lcsdid" is listed.
F

**Comment by mu2023** [comment]
Thanks, Fernando! It works with copying the files to the personal ado directory. 

Best wishes
